import React from 'react';
import LoadVideo from '../components/load-video.js';
import pluginPic from '../../media/projects/simplecrush/plugin.png';
import settingsPic from '../../media/projects/simplecrush/settings.png';
import themePic from '../../media/projects/simplecrush/themes.png';
import presetPic from '../../media/projects/simplecrush/presets.png';
import t1 from '../../media/projects/simplecrush/t1.png';
import t2 from '../../media/projects/simplecrush/t2.png';
import t3 from '../../media/projects/simplecrush/t3.png';
import t4 from '../../media/projects/simplecrush/t4.png';
import t5 from '../../media/projects/simplecrush/t5.png';
import t6 from '../../media/projects/simplecrush/t6.png';
import t7 from '../../media/projects/simplecrush/t7.png';
import demo from '../../media/projects/simplecrush/demo.mp4';
import presets from '../../media/projects/simplecrush/presets.mp4';
import { FiDownload } from "react-icons/fi";

function SimpleCrushProject() {

    const techstack = [
        { icon: <i className="devicon-cplusplus-plain"></i>, name: " C++" },
        { icon: <img src="https://cdn.simpleicons.org/juce" alt="JUCE" style={{ width: '1em', height: '1em', verticalAlign: 'middle' }} />, name: " JUCE" }
    ];

    const features = [
        "Bit Depth Reduction: Introduce quantization noise to create a characteristic lo-fi sound. Highly effective for adding texture to bass and drums.",
        "Sample Rate Reduction: Lower the sample rate to induce classic aliasing artifacts and digital degradation.",
        "Mix Control: Seamlessly blend the processed signal with the dry audio for parallel processing, ranging from subtle grit to extreme destruction.",
        "Filter Controls: Built-in high-pass and low-pass filters tame harsh high-end artifacts or muddy low-end frequencies generated by the crushing process.",
        "Custom Themes: Choose from seven lovely color palettes to match your DAW or personal aesthetic.",
        "Dedicated Settings: A centralized menu to manage theme selection, UI scale, and global plugin preferences.",
        "Preset Management: A fully featured preset system including save, delete, load, folder selection, and a randomization tool for quick inspiration.",
        "Interactive Tooltips: Hover over any control to reveal a concise description of its function, enhancing usability and reducing the learning curve.",
        "Dedicated Installer: Simplifies the installation process for end-users.",
        "Resizable UI (Work in Progress): A fully scalable interface ensures comfortable usability across any monitor size or resolution."
    ];

    const experience = [
        "Built a functional VST3 audio plugin from scratch using C++ and the JUCE framework.",
        "Deepened understanding of DSP (Digital Signal Processing) concepts, specifically bit-depth reduction and sample-rate aliasing algorithms.",
        "Optimized audio processing algorithms to balance sonic character with CPU computational efficiency.",
        "Engineered a custom preset management system, enabling users to easily save, organize, and recall parameters.",
        "Designed and implemented an intuitive, visually appealing, and fully responsive custom GUI.",
        "Refined UI/UX design skills by developing a dynamic theming system with a consistent visual language.",
        "Architected a reusable plugin development framework to streamline the creation of future VST projects.",
        "Custom mouse control code to override default JUCE knob behavior, allowing for highly precise parameter adjustments.",
        "SVG icon generation and integration for a polished, resolution-independent professional interface."
    ];

    return (
        <div className="project-page">
            <div className="project-header">
                <a href="https://github.com/sheasyve/simplecrush">
                    <h1>
                        <b>SimpleCrush</b>
                        <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                            alt="GitHub Logo" />
                    </h1>
                </a>

                <div className="techstack">
                    <ul className="tech-items" style={{ flexWrap: "nowrap", listStyle: "none", margin: "0 auto", padding: 0 }}>
                        {techstack.map((tech, index) => (
                            <li key={index} className="tech-item">
                                <h4>{tech.name}</h4>
                                {tech.icon}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="headerbg">
                    <div className="desktop-split">
                        <div className="right-content">
                            <img
                                src={pluginPic}
                                alt="SimpleCrush Plugin"
                                className="plugin-pic"
                            />
                        </div>
                        <div className="left-content">
                            <div className="description">
                                <p>SimpleCrush is a VST3 bitcrusher plugin engineered in C++ using the JUCE framework, designed for aggressive audio destruction and unique harmonic generation.</p>
                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush_v1.3.1_Windows.exe" download="SimpleCrush_v1.3.1_Windows.exe"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 Windows Installer
                                    </a>
                                </div>
                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush-macOS-Unsigned.zip" download="SimpleCrush-macOS-Unsigned.zip"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 macOS zip
                                    </a>
                                </div>
                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush.vst3.zip"
                                        download="SimpleCrush_v1.3.1.zip"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 Windows zip
                                    </a>
                                </div>
                                <p>The plugin allows users to reduce bit depth and sample rate to control digital degradation.
                                    The plugin features built-in high-pass/low-pass filters and a wet/dry mix control for parallel processing.</p>
                                <p>The latest v1.3.1 release includes a new macOS version, many bug fixes, better resizing capabilities, and the ability to add your own themes from files.</p>
                                <p>The v1.3.0 release introduces a streamlined Windows installer, an optimized codebase, and an enhanced user experience.
                                    Interactive tooltips guide new users, while custom-engineered knobs provide highly precise and responsive parameter adjustments.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="simplecrush-showcase">
                <div className="features">
                    <h2>Features</h2>
                    <ul className="feature-list" style={{ paddingBottom: '1rem', margin: '0 auto' }}>
                        {features.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>
                    <div className="plugin-vid">
                        <LoadVideo src={demo} loop controls />
                        <LoadVideo src={presets} loop controls />
                    </div>
                    <div className="settings-themes-showcase">
                        <img src={settingsPic} alt="SimpleCrush Settings" className="setting-pic" />
                        <img src={presetPic} alt="SimpleCrush Presets" className="preset-pic" />
                        <img src={themePic} alt="SimpleCrush Themes" className="setting-pic" />
                    </div>
                    <p style={{ textAlign: 'center' }}>SimpleCrush features 7 unique visual themes, accessible via the central settings menu.</p>
                    <div className="theme-grid">
                        {[t1, t2, t3, t4, t5, t6, t7].map((pic, i) => (
                            <img key={i} src={pic} alt={`Theme ${i + 1}`} className="theme-pic" />
                        ))}
                    </div>
                    <p style={{ textAlign: 'center' }}>All UI preferences, including the active theme and UI scaling, are written to a configuration file to ensure persistence across DAW sessions.</p>
                </div>

                <div className="technical-breakdown">
                    <h2>Technical Breakdown</h2>
                    <p>
                        SimpleCrush was built utilizing C++ and the JUCE framework.
                        JUCE provides a robust and flexible platform for audio plugin development, allowing for low-level, efficient handling of real-time audio streams alongside complex user interface design.
                        <br /><br />
                        The core functionality relies on custom DSP algorithms designed to introduce the characteristic quantization noise and aliasing distortion associated with classic sampler degradation.
                        The development process required iterative testing to balance sonic character with CPU computational efficiency.
                        Beyond audio processing, significant engineering was dedicated to the plugin's architecture—including a bespoke preset management system,
                        a state-saving configuration system, and customized mouse-interaction logic for refined UI control.
                    </p>
                </div>

                <div className="project-list">
                    <h2>Experience Gained</h2>
                    <ul className="experience">
                        {experience.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>
                </div>
            </div>
        </div>
    );
}

export default SimpleCrushProject;