import React from 'react';
import LoadVideo from '../components/load-video.js';
import pluginPic from '../../media/projects/simplecrush/plugin.png';
import settingsPic from '../../media/projects/simplecrush/settings.png';
import themePic from '../../media/projects/simplecrush/themes.png';
import presetPic from '../../media/projects/simplecrush/presets.png';
import t1 from '../../media/projects/simplecrush/t1.png';
import t2 from '../../media/projects/simplecrush/t2.png';
import t3 from '../../media/projects/simplecrush/t3.png';
import t4 from '../../media/projects/simplecrush/t4.png';
import t5 from '../../media/projects/simplecrush/t5.png';
import t6 from '../../media/projects/simplecrush/t6.png';
import t7 from '../../media/projects/simplecrush/t7.png';
import t8 from '../../media/projects/simplecrush/t8.png';
import chords from '../../media/projects/simplecrush/chords.mp4';
import bass from '../../media/projects/simplecrush/bass.mp4';
import house_drums from '../../media/projects/simplecrush/house_drums.mp4';
import guitar from '../../media/projects/simplecrush/guitar.mp4';

import { FiDownload } from "react-icons/fi";

function SimpleCrushProject() {

    const techstack = [
        { icon: <i className="devicon-cplusplus-plain"></i>, name: " C++" },
        { icon: <img src="https://cdn.simpleicons.org/juce" alt="JUCE" style={{ width: '1em', height: '1em', verticalAlign: 'middle' }} />, name: " JUCE" }
    ];

    const features = [
        "Bit Depth Reduction: Introduces quantization noise to create a characteristic lo-fi sound, highly effective for adding texture to bass and drums.",
        "Sample Rate Reduction: Lowers the sample rate to induce classic aliasing artifacts and digital degradation.",
        "Mix Control: Seamlessly blends the processed signal with the dry audio for parallel processing, ranging from subtle grit to total destruction.",
        "Filter Controls: Built-in high-pass and low-pass filters tame harsh high-end artifacts or muddy low-end frequencies generated by the crushing process.",
        "Custom Themes: Features 8 unique built-in color palettes, plus the ability to load custom themes from files.",
        "Dedicated Settings: A centralized menu to manage theme selection, data folders, UI scale, and global plugin preferences.",
        "Preset Management: A fully-featured preset system including save, delete, load, folder selection, and a randomization tool for quick inspiration.",
        "Interactive Tooltips: Hovering over any control reveals a concise description of its function, enhancing usability and reducing the learning curve.",
        "Dedicated Installer: Streamlines the installation process for end-users across Windows and macOS.",
        "Resizable UI: A fully scalable vector interface that ensures comfortable usability across any monitor size or resolution."
    ];

    const experience = [
        "Engineered a fully functional VST3 audio plugin from scratch utilizing C++ and the JUCE framework.",
        "Deepened understanding of DSP (Digital Signal Processing) concepts, specifically bit-depth reduction and sample-rate aliasing algorithms.",
        "Optimized audio processing to balance unique sonic character with CPU computational efficiency.",
        "Developed a robust custom preset management system, enabling users to easily save, organize, and recall parameters.",
        "Designed and implemented an intuitive, visually appealing, and responsive graphical user interface.",
        "Refined UI/UX design skills by architecting a dynamic theming system with consistent visual language.",
        "Built a reusable plugin development framework to streamline the creation of future VST projects.",
        "Wrote custom mouse-interaction logic to override default JUCE knob behavior, allowing for highly precise parameter adjustments.",
        "Generated and integrated custom SVG icons for a polished, resolution-independent professional interface."
    ];

    return (
        <div className="project-page">
            <div className="project-header">
                <a href="https://github.com/sheasyve/simplecrush">
                    <h1>
                        <b>SimpleCrush</b>
                        <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                            alt="GitHub Logo" />
                    </h1>
                </a>

                <div className="techstack">
                    <ul className="tech-items" style={{ flexWrap: "nowrap", listStyle: "none", margin: "0 auto", padding: 0 }}>
                        {techstack.map((tech, index) => (
                            <li key={index} className="tech-item">
                                <h4>{tech.name}</h4>
                                {tech.icon}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="headerbg">

                    <p className="mobile-only description-intro" style={{ marginBottom: '0', marginTop: '0', paddingTop: '1rem' }}>
                        SimpleCrush is a VST3 bitcrusher plugin engineered in C++ using the JUCE framework, designed for aggressive audio destruction and unique harmonic generation.
                    </p>

                    <div className="desktop-split">
                        <div className="right-content">
                            <img
                                src={pluginPic}
                                alt="SimpleCrush Plugin"
                                className="plugin-pic"
                            />
                        </div>
                        <div className="left-content">
                            <div className="description">

                                <p className="desktop-only description-intro">
                                    SimpleCrush is a VST3 bitcrusher plugin engineered in C++ using the JUCE framework, designed for aggressive audio destruction and unique harmonic generation.
                                </p>

                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush_v1.3.1_Windows.exe" download="SimpleCrush_v1.3.1_Windows.exe"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 Windows Installer
                                    </a>
                                </div>
                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush-macOS-Unsigned.zip" download="SimpleCrush-macOS-Unsigned.zip"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 macOS zip
                                    </a>
                                </div>
                                <div className="button-wrapper">
                                    <a href="downloads/SimpleCrush.vst3.zip"
                                        download="SimpleCrush_v1.3.1.zip"
                                        target="_blank" rel="noopener noreferrer">
                                        <FiDownload style={{ paddingRight: '1rem' }} />
                                        Download SimpleCrush v1.3.1 Windows zip
                                    </a>
                                </div>
                                <p>The plugin empowers users to reduce bit depth and sample rate to control digital degradation, featuring built-in high-pass and low-pass filters and a wet/dry mix control for parallel processing.</p>
                                <div className="release-notes-snippet">
                                    <p>v1.3.1 Includes official <strong>macOS support</strong>, improved scaling across knobs, presets, and settings menus, custom theme loading from files,
                                        refreshed color palettes, alphabetical theme sorting, an updated settings data folder button, and a refined, modular codebase.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="simplecrush-showcase">
                <div className="features">
                    <h2>Features</h2>
                    <ul className="feature-list" style={{ paddingBottom: '1rem', margin: '0 auto' }}>
                        {features.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>

                    <div className="plugin-vid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '2rem' }}>
                        <div className="video-container" style={{ textAlign: 'center' }}>
                            <h4 className="video-title"  >Chords</h4>
                            <LoadVideo src={chords} loop controls />
                        </div>
                        <div className="video-container" style={{ textAlign: 'center' }}>
                            <h4 className="video-title"  >Bass</h4>
                            <LoadVideo src={bass} loop controls />
                        </div>
                        <div className="video-container" style={{ textAlign: 'center' }}>
                            <h4 className="video-title" >House Drums</h4>
                            <LoadVideo src={house_drums} loop controls />
                        </div>
                        <div className="video-container" style={{ textAlign: 'center' }}>
                            <h4 className="video-title">Guitar</h4>
                            <LoadVideo src={guitar} loop controls />
                        </div>
                    </div>

                    <div className="settings-themes-showcase">
                        <img src={settingsPic} alt="SimpleCrush Settings" className="setting-pic" />
                        <img src={presetPic} alt="SimpleCrush Presets" className="preset-pic" />
                        <img src={themePic} alt="SimpleCrush Themes" className="setting-pic" />
                    </div>
                    <p style={{ textAlign: 'center' }}>SimpleCrush features unique visual themes, accessible via the central settings menu.</p>
                    <div className="theme-grid">
                        {[t1, t2, t3, t4, t5, t6, t7, t8].map((pic, i) => (
                            <img key={i} src={pic} alt={`Theme ${i + 1}`} className="theme-pic" />
                        ))}
                    </div>
                    <p style={{ textAlign: 'center' }}>All UI preferences, including the active theme and UI scaling, are securely written to a configuration file to ensure persistence across your DAW sessions.</p>
                </div>

                <div className="technical-breakdown">
                    <h2>Technical Breakdown</h2>
                    <p>SimpleCrush was built utilizing C++ and the JUCE framework.
                        JUCE provides a robust and flexible platform for audio plugin development, allowing for low-level, efficient handling of real-time audio streams alongside complex graphical user interface design.
                        <br /><br />
                        The core functionality relies on custom DSP algorithms built to introduce the characteristic quantization noise and aliasing distortion associated with classic sampler degradation.
                        Beyond audio processing, significant engineering was dedicated to the plugin's underlying architecture, including a bespoke preset management system,
                        a state-saving configuration system, and customized mouse-interaction logic for refined UI control.
                    </p>
                </div>

                <div className="project-list">
                    <h2>Experience Gained</h2>
                    <ul className="experience">
                        {experience.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>
                </div>
            </div>
        </div>
    );
}

export default SimpleCrushProject;