import React from 'react';
import LoadVideo from '../components/load-video.js';
import pluginPic from '../../media/projects/simplecrush/plugin.png';
import settingsPic from '../../media/projects/simplecrush/settings.png';
import themePic from '../../media/projects/simplecrush/themes.png';
import presetPic from '../../media/projects/simplecrush/presets.png';
import t1 from '../../media/projects/simplecrush/t1.png';
import t2 from '../../media/projects/simplecrush/t2.png';
import t3 from '../../media/projects/simplecrush/t3.png';
import t4 from '../../media/projects/simplecrush/t4.png';
import t5 from '../../media/projects/simplecrush/t5.png';
import t6 from '../../media/projects/simplecrush/t6.png';
import t7 from '../../media/projects/simplecrush/t7.png';
import demo from '../../media/projects/simplecrush/demo.mp4';
import presets from '../../media/projects/simplecrush/presets.mp4';
import { FiDownload } from "react-icons/fi";

function SimpleCrushProject() {

    const techstack = [{ icon: <i className="devicon-cplusplus-plain"></i>, name: " C++" },
    { icon: <img src="https://cdn.simpleicons.org/juce" alt="JUCE" style={{ width: '1em', height: '1em', verticalAlign: 'middle' }} />, name: " JUCE" }];

    const features = [
        "Bit Depth Reduction: Introduce quantization noise to create a characteristic lo-fi sound. Highly effective for adding texture to bass and drums.",
        "Sample Rate Reduction: Lower the sample rate to induce classic aliasing artifacts and digital degradation.",
        "Mix Control: Seamlessly blend the processed signal with the dry audio for parallel processing, ranging from subtle grit to extreme destruction.",
        "Filter Controls: Built-in high-pass and low-pass filters tame harsh high-end artifacts or muddy low-end frequencies generated by the crushing process.",
        "Custom Themes: Choose from seven unique color palettes to match your DAW or personal aesthetic.",
        "Dedicated Settings: A centralized menu to manage theme selection, UI scale, and global plugin preferences.",
        "Preset Management: A fully featured preset system including save, delete, load, folder selection, and a randomization tool for quick inspiration.",
        "Resizable UI: A fully scalable interface ensures comfortable usability across any monitor size or resolution."
    ];

    const experience = [
        "Built a functional VST3 audio plugin from scratch using C++ and the JUCE framework.",
        "Deepened understanding of DSP (Digital Signal Processing) concepts, specifically bit-depth reduction and sample-rate aliasing algorithms.",
        "Optimized audio processing algorithms to balance sonic character with CPU computational efficiency.",
        "Engineered a custom preset management system, enabling users to easily save, organize, and recall parameters.",
        "Designed and implemented an intuitive, visually appealing, and fully responsive custom GUI.",
        "Refined UI/UX design skills by developing a dynamic theming system with a consistent visual language.",
        "Architected a reusable plugin development framework to streamline the creation of future VST projects."
    ];

    return (
        <div className="project-page">
            <div className="project-header">
                <a href="https://github.com/sheasyve/simplecrush">
                    <h1>
                        <b>SimpleCrush</b>
                        <img
                            src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                            alt="GitHub Logo"
                        />
                    </h1>
                </a>

                <div className="techstack">
                    <ul className="tech-items" style={{ flexWrap: "nowrap", listStyle: "none", margin: "0 auto", padding: 0 }}>
                        {techstack.map((tech, index) => (
                            <li key={index} className="tech-item">
                                <h4>{tech.name}</h4>
                                {tech.icon}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="headerbg">
                    <div className="desktop-split">
                        <div className="right-content">
                            <img
                                src={pluginPic}
                                alt="SimpleCrush Plugin"
                                className="plugin-pic"
                            />
                        </div>
                        <div className="left-content">
                            <div className="description">
                                <p>SimpleCrush is a VST3 bitcrusher plugin built with C++ and the JUCE framework.</p>
                                <div className="button-wrapper">
                                    <a
                                        href="downloads/SimpleCrush_v1.3.0_Windows.exe"
                                        download="SimpleCrush_v1.3.0.exe"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        <FiDownload style={{ paddingRight: '1rem' }} /> 
                                        Download SimpleCrush v1.3.0 Installer
                                    </a>
                                </div>
                                <div className="button-wrapper">
                                    <a
                                        href="downloads/SimpleCrush.vst3.zip"
                                        download="SimpleCrush_v1.3.0.vst3.zip"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                    >
                                        <FiDownload style={{ paddingRight: '1rem' }} /> 
                                        Download SimpleCrush v1.3.0 zip
                                    </a>
                                </div>
                                <p>The plugin allows users to reduce the bit depth and sample rate of audio, with built in mix and filter controls.
                                    There is also a settings menu with 7 unique color themes, a resizing tool, and a preset system with a randomizer just released in v1.2.0
                                </p>
                                <p>Currently I am working on bundling it with an installer, cleaning up the code base, and adding hover hints to the knobs and buttons. The hover hints can be toggled in the settings menu.
                                    After that, I will be working on tuning the audio engine and knob behavior, and then completing a visual overhaul.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="simplecrush-showcase">
                <div className="features">
                    <h2>Features</h2>
                    <ul className="feature-list" style={{ paddingBottom: '1rem', margin: '0 auto' }}>
                        {features.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>
                    <div className="plugin-vid">
                        <LoadVideo src={demo} loop controls />
                        <LoadVideo src={presets} loop controls />
                    </div>
                    <div className="settings-themes-showcase">
                        <img src={settingsPic} alt="SimpleCrush Settings" className="setting-pic" />
                        <img src={presetPic} alt="SimpleCrush Presets" className="preset-pic" />
                        <img src={themePic} alt="SimpleCrush Themes" className="setting-pic" />
                    </div>
                    <p style={{ textAlign: 'center' }}>I have now finished implementing 7 unique themes that can be selected in the settings menu.</p>
                    <div className="theme-grid">
                        {[t1, t2, t3, t4, t5, t6, t7].map((pic, i) => (
                            <img key={i} src={pic} alt={`Theme ${i + 1}`} className="theme-pic" />
                        ))}
                    </div>
                    <p style={{ textAlign: 'center' }}>The settings are saved in a file which is loaded on startup to be persistent across sessions.</p>
                </div>

                <div className="technical-breakdown">
                    <h2>Technical Breakdown</h2>
                    <p>The plugin was built using C++ and the JUCE framework.
                        JUCE provides a powerful and flexible platform for audio plugin development, allowing for efficient handling of audio processing and user interface design. The plugin's core functionality is implemented in C++, leveraging JUCE's audio processing capabilities to manipulate the audio signal in real-time.
                        <br></br><br></br>
                        The bit depth and sample rate reduction algorithms are designed to introduce the characteristic distortion associated with bitcrushing, while the mix and filter controls allow users to remove unpleasant high and low frequencies. The development process involved iterating on the audio processing algorithms to achieve the desired sound quality and performance, as well as designing an intuitive user interface for seamless interaction with the plugin.</p>
                </div>

                <div className="project-list">
                    <h2>Experience Gained</h2>
                    <ul className="experience">
                        {experience.map((exp, index) => (
                            <li key={index}>{exp}</li>))}
                    </ul>
                </div>
            </div>
        </div>
    );
}

export default SimpleCrushProject;